# Generated by Django 4.0.1 on 2022-01-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
